#!/usr/bin/env bash

REALSENSE_FOXY_SETUP="${REALSENSE_FOXY_SETUP:-/opt/ros/foxy/setup.bash}"
REALSENSE_256_PREFIX="${REALSENSE_256_PREFIX:-/home/unitree/librealsense-2.56.5-install}"
REALSENSE_456_SETUP="${REALSENSE_456_SETUP:-/home/unitree/ros2_realsense_456_ws/install/local_setup.bash}"
REALSENSE_RMW_IMPLEMENTATION="${REALSENSE_RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"
REALSENSE_FASTDDS_PROFILE="${REALSENSE_FASTDDS_PROFILE:-/home/unitree/ros2_realsense_456_ws/fastdds_go2.xml}"

source "${REALSENSE_FOXY_SETUP}"

export PATH="${REALSENSE_256_PREFIX}/bin${PATH:+:${PATH}}"
export CMAKE_PREFIX_PATH="${REALSENSE_256_PREFIX}${CMAKE_PREFIX_PATH:+:${CMAKE_PREFIX_PATH}}"
export LD_LIBRARY_PATH="${REALSENSE_256_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export RMW_IMPLEMENTATION="${REALSENSE_RMW_IMPLEMENTATION}"
export FASTRTPS_DEFAULT_PROFILES_FILE="${REALSENSE_FASTDDS_PROFILE}"

source "${REALSENSE_456_SETUP}"
